const { Client } = require('pg');

const CORS_HEADERS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type'
};

exports.handler = async (event) => {
  if (event.httpMethod === 'OPTIONS') {
    return { statusCode: 200, headers: CORS_HEADERS, body: '' };
  }

  if (event.httpMethod !== 'POST') {
    return {
      statusCode: 405,
      headers: CORS_HEADERS,
      body: JSON.stringify({ error: 'Method not allowed. Use POST.' })
    };
  }

  let body;
  try {
    body = JSON.parse(event.body || '{}');
  } catch (err) {
    return {
      statusCode: 400,
      headers: CORS_HEADERS,
      body: JSON.stringify({ error: 'Invalid JSON body.' })
    };
  }

  const { connectionString, statements } = body;

  if (!connectionString || typeof connectionString !== 'string') {
    return {
      statusCode: 400,
      headers: CORS_HEADERS,
      body: JSON.stringify({ error: 'Missing or invalid connectionString.' })
    };
  }

  // statements: array of SQL strings, expected to be [CREATE TABLE, ...INSERTs]
  // generated by csvsql.js, run in order inside a single transaction
  if (!Array.isArray(statements) || statements.length === 0) {
    return {
      statusCode: 400,
      headers: CORS_HEADERS,
      body: JSON.stringify({ error: 'Missing or empty statements array.' })
    };
  }

  const client = new Client({
    connectionString,
    ssl: { rejectUnauthorized: false },
    connectionTimeoutMillis: 8000
  });

  try {
    await client.connect();
  } catch (err) {
    await client.end().catch(() => {});
    return {
      statusCode: 502,
      headers: CORS_HEADERS,
      body: JSON.stringify({ error: `Could not connect to database: ${err.message}` })
    };
  }

  try {
    await client.query('SET statement_timeout = 15000');
    await client.query('BEGIN');
    for (const stmt of statements) {
      if (typeof stmt === 'string' && stmt.trim()) {
        await client.query(stmt);
      }
    }
    await client.query('COMMIT');
    await client.end();

    return {
      statusCode: 200,
      headers: CORS_HEADERS,
      body: JSON.stringify({ success: true, statementsRun: statements.length })
    };
  } catch (err) {
    await client.query('ROLLBACK').catch(() => {});
    await client.end().catch(() => {});
    return {
      statusCode: 400,
      headers: CORS_HEADERS,
      body: JSON.stringify({ error: `Insert failed: ${err.message}` })
    };
  }
};
