const { Client } = require('pg');

module.exports = async (req, res) => {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }

  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed. Use POST.' });
  }

  const { connectionString, statements } = req.body || {};

  if (!connectionString || typeof connectionString !== 'string') {
    return res.status(400).json({ error: 'Missing or invalid connectionString.' });
  }

  // statements: array of SQL strings, expected to be [CREATE TABLE, ...INSERTs]
  // generated by csvsql.js, run in order inside a single transaction
  if (!Array.isArray(statements) || statements.length === 0) {
    return res.status(400).json({ error: 'Missing or empty statements array.' });
  }

  const client = new Client({
    connectionString,
    ssl: { rejectUnauthorized: false }
  });

  try {
    await client.connect();
  } catch (err) {
    await client.end().catch(() => {});
    return res.status(502).json({ error: `Could not connect to database: ${err.message}` });
  }

  try {
    await client.query('BEGIN');
    for (const stmt of statements) {
      if (typeof stmt === 'string' && stmt.trim()) {
        await client.query(stmt);
      }
    }
    await client.query('COMMIT');
    await client.end();

    return res.status(200).json({ success: true, statementsRun: statements.length });
  } catch (err) {
    await client.query('ROLLBACK').catch(() => {});
    await client.end().catch(() => {});
    return res.status(400).json({ error: `Insert failed: ${err.message}` });
  }
};
